# Generated by Django 2.0.3 on 2018-04-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
